[2025-07-19T18:04:04.738+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: restaurant_pipeline.stream_to_bronze scheduled__2025-07-19T18:02:00+00:00 [queued]>
[2025-07-19T18:04:04.742+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: restaurant_pipeline.stream_to_bronze scheduled__2025-07-19T18:02:00+00:00 [queued]>
[2025-07-19T18:04:04.742+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-07-19T18:04:04.750+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): stream_to_bronze> on 2025-07-19 18:02:00+00:00
[2025-07-19T18:04:04.752+0000] {standard_task_runner.py:57} INFO - Started process 276 to run task
[2025-07-19T18:04:04.754+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'restaurant_pipeline', 'stream_to_bronze', 'scheduled__2025-07-19T18:02:00+00:00', '--job-id', '924', '--raw', '--subdir', 'DAGS_FOLDER/restaurant_pipeline.py', '--cfg-path', '/tmp/tmpu_neiazb']
[2025-07-19T18:04:04.755+0000] {standard_task_runner.py:85} INFO - Job 924: Subtask stream_to_bronze
[2025-07-19T18:04:04.776+0000] {task_command.py:416} INFO - Running <TaskInstance: restaurant_pipeline.stream_to_bronze scheduled__2025-07-19T18:02:00+00:00 [running]> on host e3f5d8fc4eef
[2025-07-19T18:04:04.811+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your@email.com' AIRFLOW_CTX_DAG_OWNER='moran' AIRFLOW_CTX_DAG_ID='restaurant_pipeline' AIRFLOW_CTX_TASK_ID='stream_to_bronze' AIRFLOW_CTX_EXECUTION_DATE='2025-07-19T18:02:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-19T18:02:00+00:00'
[2025-07-19T18:04:04.811+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-19T18:04:04.812+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "docker exec -e AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-19T18:02:00+00:00' spark-iceberg spark-submit /home/iceberg/spark/stream_to_bronze.py"]
[2025-07-19T18:04:04.815+0000] {subprocess.py:86} INFO - Output:
[2025-07-19T18:04:06.083+0000] {subprocess.py:93} INFO - 25/07/19 18:04:06 INFO SparkContext: Running Spark version 3.5.6
[2025-07-19T18:04:06.084+0000] {subprocess.py:93} INFO - 25/07/19 18:04:06 INFO SparkContext: OS info Linux, 6.10.14-linuxkit, aarch64
[2025-07-19T18:04:06.084+0000] {subprocess.py:93} INFO - 25/07/19 18:04:06 INFO SparkContext: Java version 17.0.15
[2025-07-19T18:04:06.098+0000] {subprocess.py:93} INFO - 25/07/19 18:04:06 INFO ResourceUtils: ==============================================================
[2025-07-19T18:04:06.098+0000] {subprocess.py:93} INFO - 25/07/19 18:04:06 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-07-19T18:04:06.098+0000] {subprocess.py:93} INFO - 25/07/19 18:04:06 INFO ResourceUtils: ==============================================================
[2025-07-19T18:04:06.099+0000] {subprocess.py:93} INFO - 25/07/19 18:04:06 INFO SparkContext: Submitted application: StreamToBronze
[2025-07-19T18:04:06.107+0000] {subprocess.py:93} INFO - 25/07/19 18:04:06 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-07-19T18:04:06.112+0000] {subprocess.py:93} INFO - 25/07/19 18:04:06 INFO ResourceProfile: Limiting resource is cpu
[2025-07-19T18:04:06.112+0000] {subprocess.py:93} INFO - 25/07/19 18:04:06 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-07-19T18:04:06.136+0000] {subprocess.py:93} INFO - 25/07/19 18:04:06 INFO SecurityManager: Changing view acls to: root,spark
[2025-07-19T18:04:06.137+0000] {subprocess.py:93} INFO - 25/07/19 18:04:06 INFO SecurityManager: Changing modify acls to: root,spark
[2025-07-19T18:04:06.137+0000] {subprocess.py:93} INFO - 25/07/19 18:04:06 INFO SecurityManager: Changing view acls groups to:
[2025-07-19T18:04:06.137+0000] {subprocess.py:93} INFO - 25/07/19 18:04:06 INFO SecurityManager: Changing modify acls groups to:
[2025-07-19T18:04:06.137+0000] {subprocess.py:93} INFO - 25/07/19 18:04:06 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: root, spark; groups with view permissions: EMPTY; users with modify permissions: root, spark; groups with modify permissions: EMPTY
[2025-07-19T18:04:06.165+0000] {subprocess.py:93} INFO - 25/07/19 18:04:06 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-07-19T18:04:06.271+0000] {subprocess.py:93} INFO - 25/07/19 18:04:06 INFO Utils: Successfully started service 'sparkDriver' on port 43865.
[2025-07-19T18:04:06.284+0000] {subprocess.py:93} INFO - 25/07/19 18:04:06 INFO SparkEnv: Registering MapOutputTracker
[2025-07-19T18:04:06.306+0000] {subprocess.py:93} INFO - 25/07/19 18:04:06 INFO SparkEnv: Registering BlockManagerMaster
[2025-07-19T18:04:06.313+0000] {subprocess.py:93} INFO - 25/07/19 18:04:06 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-07-19T18:04:06.313+0000] {subprocess.py:93} INFO - 25/07/19 18:04:06 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-07-19T18:04:06.315+0000] {subprocess.py:93} INFO - 25/07/19 18:04:06 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-07-19T18:04:06.325+0000] {subprocess.py:93} INFO - 25/07/19 18:04:06 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-deaf252f-669b-4306-b678-dbe8feb17171
[2025-07-19T18:04:06.332+0000] {subprocess.py:93} INFO - 25/07/19 18:04:06 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-07-19T18:04:06.339+0000] {subprocess.py:93} INFO - 25/07/19 18:04:06 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-07-19T18:04:06.391+0000] {subprocess.py:93} INFO - 25/07/19 18:04:06 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-07-19T18:04:06.425+0000] {subprocess.py:93} INFO - 25/07/19 18:04:06 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-07-19T18:04:06.473+0000] {subprocess.py:93} INFO - 25/07/19 18:04:06 INFO Executor: Starting executor ID driver on host 8b44f3d35cfa
[2025-07-19T18:04:06.474+0000] {subprocess.py:93} INFO - 25/07/19 18:04:06 INFO Executor: OS info Linux, 6.10.14-linuxkit, aarch64
[2025-07-19T18:04:06.474+0000] {subprocess.py:93} INFO - 25/07/19 18:04:06 INFO Executor: Java version 17.0.15
[2025-07-19T18:04:06.476+0000] {subprocess.py:93} INFO - 25/07/19 18:04:06 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-07-19T18:04:06.476+0000] {subprocess.py:93} INFO - 25/07/19 18:04:06 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@756fefb3 for default.
[2025-07-19T18:04:06.485+0000] {subprocess.py:93} INFO - 25/07/19 18:04:06 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 43721.
[2025-07-19T18:04:06.486+0000] {subprocess.py:93} INFO - 25/07/19 18:04:06 INFO NettyBlockTransferService: Server created on 8b44f3d35cfa:43721
[2025-07-19T18:04:06.486+0000] {subprocess.py:93} INFO - 25/07/19 18:04:06 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-07-19T18:04:06.493+0000] {subprocess.py:93} INFO - 25/07/19 18:04:06 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 8b44f3d35cfa, 43721, None)
[2025-07-19T18:04:06.494+0000] {subprocess.py:93} INFO - 25/07/19 18:04:06 INFO BlockManagerMasterEndpoint: Registering block manager 8b44f3d35cfa:43721 with 434.4 MiB RAM, BlockManagerId(driver, 8b44f3d35cfa, 43721, None)
[2025-07-19T18:04:06.498+0000] {subprocess.py:93} INFO - 25/07/19 18:04:06 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 8b44f3d35cfa, 43721, None)
[2025-07-19T18:04:06.498+0000] {subprocess.py:93} INFO - 25/07/19 18:04:06 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 8b44f3d35cfa, 43721, None)
[2025-07-19T18:04:06.700+0000] {subprocess.py:93} INFO - 25/07/19 18:04:06 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-07-19T18:04:06.704+0000] {subprocess.py:93} INFO - 25/07/19 18:04:06 INFO SharedState: Warehouse path is 'file:/app/spark-warehouse'.
[2025-07-19T18:04:07.643+0000] {subprocess.py:93} INFO - 25/07/19 18:04:07 WARN MetricsConfig: Cannot locate configuration: tried hadoop-metrics2-s3a-file-system.properties,hadoop-metrics2.properties
[2025-07-19T18:04:07.651+0000] {subprocess.py:93} INFO - 25/07/19 18:04:07 INFO MetricsSystemImpl: Scheduled Metric snapshot period at 10 second(s).
[2025-07-19T18:04:07.652+0000] {subprocess.py:93} INFO - 25/07/19 18:04:07 INFO MetricsSystemImpl: s3a-file-system metrics system started
[2025-07-19T18:04:08.276+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-19T18:04:08.276+0000] {subprocess.py:93} INFO -   File "/home/iceberg/spark/stream_to_bronze.py", line 93, in <module>
[2025-07-19T18:04:08.276+0000] {subprocess.py:93} INFO -     read_kafka(
[2025-07-19T18:04:08.277+0000] {subprocess.py:93} INFO -   File "/home/iceberg/spark/stream_to_bronze.py", line 89, in read_kafka
[2025-07-19T18:04:08.277+0000] {subprocess.py:93} INFO -     .start()
[2025-07-19T18:04:08.277+0000] {subprocess.py:93} INFO -      ^^^^^^^
[2025-07-19T18:04:08.277+0000] {subprocess.py:93} INFO -   File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/sql/streaming/readwriter.py", line 1527, in start
[2025-07-19T18:04:08.277+0000] {subprocess.py:93} INFO -   File "/opt/bitnami/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-07-19T18:04:08.277+0000] {subprocess.py:93} INFO -   File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
[2025-07-19T18:04:08.278+0000] {subprocess.py:93} INFO -   File "/opt/bitnami/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2025-07-19T18:04:08.278+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o67.start.
[2025-07-19T18:04:08.279+0000] {subprocess.py:93} INFO - : org.apache.iceberg.exceptions.NoSuchTableException: Cannot find table for bronze.Reservations_raw.
[2025-07-19T18:04:08.279+0000] {subprocess.py:93} INFO - 	at org.apache.iceberg.spark.source.IcebergSource.getTable(IcebergSource.java:112)
[2025-07-19T18:04:08.279+0000] {subprocess.py:93} INFO - 	at org.apache.iceberg.spark.source.IcebergSource.inferPartitioning(IcebergSource.java:90)
[2025-07-19T18:04:08.280+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Utils$.getTableFromProvider(DataSourceV2Utils.scala:82)
[2025-07-19T18:04:08.280+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.streaming.DataStreamWriter.startInternal(DataStreamWriter.scala:399)
[2025-07-19T18:04:08.280+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.streaming.DataStreamWriter.start(DataStreamWriter.scala:251)
[2025-07-19T18:04:08.280+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-07-19T18:04:08.280+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[2025-07-19T18:04:08.280+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[2025-07-19T18:04:08.280+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[2025-07-19T18:04:08.280+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-07-19T18:04:08.280+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-07-19T18:04:08.280+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-07-19T18:04:08.280+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-07-19T18:04:08.280+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-07-19T18:04:08.281+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-07-19T18:04:08.281+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-07-19T18:04:08.281+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Unknown Source)
[2025-07-19T18:04:08.281+0000] {subprocess.py:93} INFO - Caused by: org.apache.spark.sql.catalyst.analysis.NoSuchTableException: [TABLE_OR_VIEW_NOT_FOUND] The table or view bronze.Reservations_raw cannot be found. Verify the spelling and correctness of the schema and catalog.
[2025-07-19T18:04:08.281+0000] {subprocess.py:93} INFO - If you did not qualify the name with a schema, verify the current_schema() output, or qualify the name with the correct schema and catalog.
[2025-07-19T18:04:08.281+0000] {subprocess.py:93} INFO - To tolerate the error on drop use DROP VIEW IF EXISTS or DROP TABLE IF EXISTS.
[2025-07-19T18:04:08.281+0000] {subprocess.py:93} INFO - 	at org.apache.iceberg.spark.SparkCatalog.loadTable(SparkCatalog.java:161)
[2025-07-19T18:04:08.281+0000] {subprocess.py:93} INFO - 	at org.apache.iceberg.spark.source.IcebergSource.getTable(IcebergSource.java:107)
[2025-07-19T18:04:08.281+0000] {subprocess.py:93} INFO - 	... 16 more
[2025-07-19T18:04:08.281+0000] {subprocess.py:93} INFO - 
[2025-07-19T18:04:08.304+0000] {subprocess.py:93} INFO - 25/07/19 18:04:08 INFO SparkContext: Invoking stop() from shutdown hook
[2025-07-19T18:04:08.304+0000] {subprocess.py:93} INFO - 25/07/19 18:04:08 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-07-19T18:04:08.310+0000] {subprocess.py:93} INFO - 25/07/19 18:04:08 INFO SparkUI: Stopped Spark web UI at http://8b44f3d35cfa:4040
[2025-07-19T18:04:08.316+0000] {subprocess.py:93} INFO - 25/07/19 18:04:08 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-07-19T18:04:08.322+0000] {subprocess.py:93} INFO - 25/07/19 18:04:08 INFO MemoryStore: MemoryStore cleared
[2025-07-19T18:04:08.322+0000] {subprocess.py:93} INFO - 25/07/19 18:04:08 INFO BlockManager: BlockManager stopped
[2025-07-19T18:04:08.325+0000] {subprocess.py:93} INFO - 25/07/19 18:04:08 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-07-19T18:04:08.327+0000] {subprocess.py:93} INFO - 25/07/19 18:04:08 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-07-19T18:04:08.331+0000] {subprocess.py:93} INFO - 25/07/19 18:04:08 INFO SparkContext: Successfully stopped SparkContext
[2025-07-19T18:04:08.331+0000] {subprocess.py:93} INFO - 25/07/19 18:04:08 INFO ShutdownHookManager: Shutdown hook called
[2025-07-19T18:04:08.331+0000] {subprocess.py:93} INFO - 25/07/19 18:04:08 INFO ShutdownHookManager: Deleting directory /tmp/spark-c36fa410-fb1c-47ee-8a8b-43a8dd728a8f/pyspark-5be2b8da-d926-4481-b1b5-497b027227ec
[2025-07-19T18:04:08.332+0000] {subprocess.py:93} INFO - 25/07/19 18:04:08 INFO ShutdownHookManager: Deleting directory /tmp/spark-5ae330e1-b6a5-447f-957e-a8ece2ce9b37
[2025-07-19T18:04:08.334+0000] {subprocess.py:93} INFO - 25/07/19 18:04:08 INFO ShutdownHookManager: Deleting directory /tmp/spark-c36fa410-fb1c-47ee-8a8b-43a8dd728a8f
[2025-07-19T18:04:08.336+0000] {subprocess.py:93} INFO - 25/07/19 18:04:08 INFO MetricsSystemImpl: Stopping s3a-file-system metrics system...
[2025-07-19T18:04:08.337+0000] {subprocess.py:93} INFO - 25/07/19 18:04:08 INFO MetricsSystemImpl: s3a-file-system metrics system stopped.
[2025-07-19T18:04:08.337+0000] {subprocess.py:93} INFO - 25/07/19 18:04:08 INFO MetricsSystemImpl: s3a-file-system metrics system shutdown complete.
[2025-07-19T18:04:08.365+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-19T18:04:08.371+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-19T18:04:08.373+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=restaurant_pipeline, task_id=stream_to_bronze, execution_date=20250719T180200, start_date=20250719T180404, end_date=20250719T180408
[2025-07-19T18:04:08.384+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2025-07-19T18:04:08.385+0000] {configuration.py:1050} WARNING - section/key [smtp/smtp_user] not found in config
[2025-07-19T18:04:08.385+0000] {email.py:270} INFO - Email alerting: attempt 1
[2025-07-19T18:04:08.388+0000] {configuration.py:1050} WARNING - section/key [smtp/smtp_user] not found in config
[2025-07-19T18:04:08.389+0000] {email.py:270} INFO - Email alerting: attempt 1
[2025-07-19T18:04:08.389+0000] {taskinstance.py:2007} ERROR - Failed to send email to: ['your@email.com']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1681, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1744, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2420, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2005, in handle_failure
    self.email_alert(error, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2422, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2025-07-19T18:04:08.395+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 924 for task stream_to_bronze (Bash command failed. The command returned a non-zero exit code 1.; 276)
[2025-07-19T18:04:08.430+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-07-19T18:04:08.455+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
