[2025-07-19T18:02:05.161+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: restaurant_pipeline.stream_to_bronze scheduled__2025-07-19T18:00:00+00:00 [queued]>
[2025-07-19T18:02:05.202+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: restaurant_pipeline.stream_to_bronze scheduled__2025-07-19T18:00:00+00:00 [queued]>
[2025-07-19T18:02:05.202+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-07-19T18:02:05.208+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): stream_to_bronze> on 2025-07-19 18:00:00+00:00
[2025-07-19T18:02:05.210+0000] {standard_task_runner.py:57} INFO - Started process 223 to run task
[2025-07-19T18:02:05.213+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'restaurant_pipeline', 'stream_to_bronze', 'scheduled__2025-07-19T18:00:00+00:00', '--job-id', '918', '--raw', '--subdir', 'DAGS_FOLDER/restaurant_pipeline.py', '--cfg-path', '/tmp/tmp747oija0']
[2025-07-19T18:02:05.214+0000] {standard_task_runner.py:85} INFO - Job 918: Subtask stream_to_bronze
[2025-07-19T18:02:05.237+0000] {task_command.py:416} INFO - Running <TaskInstance: restaurant_pipeline.stream_to_bronze scheduled__2025-07-19T18:00:00+00:00 [running]> on host e3f5d8fc4eef
[2025-07-19T18:02:05.285+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your@email.com' AIRFLOW_CTX_DAG_OWNER='moran' AIRFLOW_CTX_DAG_ID='restaurant_pipeline' AIRFLOW_CTX_TASK_ID='stream_to_bronze' AIRFLOW_CTX_EXECUTION_DATE='2025-07-19T18:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-19T18:00:00+00:00'
[2025-07-19T18:02:05.286+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-19T18:02:05.286+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "docker exec -e AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-19T18:00:00+00:00' spark-iceberg spark-submit /home/iceberg/spark/stream_to_bronze.py"]
[2025-07-19T18:02:05.291+0000] {subprocess.py:86} INFO - Output:
[2025-07-19T18:02:07.249+0000] {subprocess.py:93} INFO - 25/07/19 18:02:07 INFO SparkContext: Running Spark version 3.5.6
[2025-07-19T18:02:07.250+0000] {subprocess.py:93} INFO - 25/07/19 18:02:07 INFO SparkContext: OS info Linux, 6.10.14-linuxkit, aarch64
[2025-07-19T18:02:07.251+0000] {subprocess.py:93} INFO - 25/07/19 18:02:07 INFO SparkContext: Java version 17.0.15
[2025-07-19T18:02:07.264+0000] {subprocess.py:93} INFO - 25/07/19 18:02:07 INFO ResourceUtils: ==============================================================
[2025-07-19T18:02:07.264+0000] {subprocess.py:93} INFO - 25/07/19 18:02:07 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-07-19T18:02:07.265+0000] {subprocess.py:93} INFO - 25/07/19 18:02:07 INFO ResourceUtils: ==============================================================
[2025-07-19T18:02:07.265+0000] {subprocess.py:93} INFO - 25/07/19 18:02:07 INFO SparkContext: Submitted application: StreamToBronze
[2025-07-19T18:02:07.274+0000] {subprocess.py:93} INFO - 25/07/19 18:02:07 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-07-19T18:02:07.278+0000] {subprocess.py:93} INFO - 25/07/19 18:02:07 INFO ResourceProfile: Limiting resource is cpu
[2025-07-19T18:02:07.278+0000] {subprocess.py:93} INFO - 25/07/19 18:02:07 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-07-19T18:02:07.308+0000] {subprocess.py:93} INFO - 25/07/19 18:02:07 INFO SecurityManager: Changing view acls to: root,spark
[2025-07-19T18:02:07.308+0000] {subprocess.py:93} INFO - 25/07/19 18:02:07 INFO SecurityManager: Changing modify acls to: root,spark
[2025-07-19T18:02:07.308+0000] {subprocess.py:93} INFO - 25/07/19 18:02:07 INFO SecurityManager: Changing view acls groups to:
[2025-07-19T18:02:07.308+0000] {subprocess.py:93} INFO - 25/07/19 18:02:07 INFO SecurityManager: Changing modify acls groups to:
[2025-07-19T18:02:07.308+0000] {subprocess.py:93} INFO - 25/07/19 18:02:07 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: root, spark; groups with view permissions: EMPTY; users with modify permissions: root, spark; groups with modify permissions: EMPTY
[2025-07-19T18:02:07.346+0000] {subprocess.py:93} INFO - 25/07/19 18:02:07 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-07-19T18:02:07.492+0000] {subprocess.py:93} INFO - 25/07/19 18:02:07 INFO Utils: Successfully started service 'sparkDriver' on port 35683.
[2025-07-19T18:02:07.515+0000] {subprocess.py:93} INFO - 25/07/19 18:02:07 INFO SparkEnv: Registering MapOutputTracker
[2025-07-19T18:02:07.536+0000] {subprocess.py:93} INFO - 25/07/19 18:02:07 INFO SparkEnv: Registering BlockManagerMaster
[2025-07-19T18:02:07.546+0000] {subprocess.py:93} INFO - 25/07/19 18:02:07 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-07-19T18:02:07.547+0000] {subprocess.py:93} INFO - 25/07/19 18:02:07 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-07-19T18:02:07.548+0000] {subprocess.py:93} INFO - 25/07/19 18:02:07 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-07-19T18:02:07.562+0000] {subprocess.py:93} INFO - 25/07/19 18:02:07 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-0dabd2e7-92d7-479c-bc8f-a76f73a83bc8
[2025-07-19T18:02:07.569+0000] {subprocess.py:93} INFO - 25/07/19 18:02:07 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-07-19T18:02:07.579+0000] {subprocess.py:93} INFO - 25/07/19 18:02:07 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-07-19T18:02:07.649+0000] {subprocess.py:93} INFO - 25/07/19 18:02:07 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-07-19T18:02:07.685+0000] {subprocess.py:93} INFO - 25/07/19 18:02:07 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-07-19T18:02:07.741+0000] {subprocess.py:93} INFO - 25/07/19 18:02:07 INFO Executor: Starting executor ID driver on host 8b44f3d35cfa
[2025-07-19T18:02:07.741+0000] {subprocess.py:93} INFO - 25/07/19 18:02:07 INFO Executor: OS info Linux, 6.10.14-linuxkit, aarch64
[2025-07-19T18:02:07.741+0000] {subprocess.py:93} INFO - 25/07/19 18:02:07 INFO Executor: Java version 17.0.15
[2025-07-19T18:02:07.744+0000] {subprocess.py:93} INFO - 25/07/19 18:02:07 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-07-19T18:02:07.744+0000] {subprocess.py:93} INFO - 25/07/19 18:02:07 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@47ff8ca4 for default.
[2025-07-19T18:02:07.762+0000] {subprocess.py:93} INFO - 25/07/19 18:02:07 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 39003.
[2025-07-19T18:02:07.762+0000] {subprocess.py:93} INFO - 25/07/19 18:02:07 INFO NettyBlockTransferService: Server created on 8b44f3d35cfa:39003
[2025-07-19T18:02:07.762+0000] {subprocess.py:93} INFO - 25/07/19 18:02:07 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-07-19T18:02:07.766+0000] {subprocess.py:93} INFO - 25/07/19 18:02:07 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 8b44f3d35cfa, 39003, None)
[2025-07-19T18:02:07.767+0000] {subprocess.py:93} INFO - 25/07/19 18:02:07 INFO BlockManagerMasterEndpoint: Registering block manager 8b44f3d35cfa:39003 with 434.4 MiB RAM, BlockManagerId(driver, 8b44f3d35cfa, 39003, None)
[2025-07-19T18:02:07.768+0000] {subprocess.py:93} INFO - 25/07/19 18:02:07 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 8b44f3d35cfa, 39003, None)
[2025-07-19T18:02:07.769+0000] {subprocess.py:93} INFO - 25/07/19 18:02:07 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 8b44f3d35cfa, 39003, None)
[2025-07-19T18:02:08.027+0000] {subprocess.py:93} INFO - 25/07/19 18:02:08 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-07-19T18:02:08.036+0000] {subprocess.py:93} INFO - 25/07/19 18:02:08 INFO SharedState: Warehouse path is 'file:/app/spark-warehouse'.
[2025-07-19T18:02:09.120+0000] {subprocess.py:93} INFO - 25/07/19 18:02:09 WARN MetricsConfig: Cannot locate configuration: tried hadoop-metrics2-s3a-file-system.properties,hadoop-metrics2.properties
[2025-07-19T18:02:09.126+0000] {subprocess.py:93} INFO - 25/07/19 18:02:09 INFO MetricsSystemImpl: Scheduled Metric snapshot period at 10 second(s).
[2025-07-19T18:02:09.126+0000] {subprocess.py:93} INFO - 25/07/19 18:02:09 INFO MetricsSystemImpl: s3a-file-system metrics system started
[2025-07-19T18:02:09.620+0000] {subprocess.py:93} INFO - 25/07/19 18:02:09 WARN HadoopTableOperations: Error trying to recover version-hint.txt data for s3a://warehouse/bronze/Reservations_raw/metadata/version-hint.text
[2025-07-19T18:02:09.620+0000] {subprocess.py:93} INFO - java.io.FileNotFoundException: No such file or directory: s3a://warehouse/bronze/Reservations_raw/metadata/version-hint.text
[2025-07-19T18:02:09.620+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.s3GetFileStatus(S3AFileSystem.java:3866)
[2025-07-19T18:02:09.620+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.innerGetFileStatus(S3AFileSystem.java:3688)
[2025-07-19T18:02:09.620+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.extractOrFetchSimpleFileStatus(S3AFileSystem.java:5401)
[2025-07-19T18:02:09.620+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.open(S3AFileSystem.java:1465)
[2025-07-19T18:02:09.620+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.open(S3AFileSystem.java:1441)
[2025-07-19T18:02:09.620+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:976)
[2025-07-19T18:02:09.620+0000] {subprocess.py:93} INFO - 	at org.apache.iceberg.hadoop.HadoopTableOperations.findVersion(HadoopTableOperations.java:318)
[2025-07-19T18:02:09.620+0000] {subprocess.py:93} INFO - 	at org.apache.iceberg.hadoop.HadoopTableOperations.refresh(HadoopTableOperations.java:104)
[2025-07-19T18:02:09.621+0000] {subprocess.py:93} INFO - 	at org.apache.iceberg.hadoop.HadoopTableOperations.current(HadoopTableOperations.java:84)
[2025-07-19T18:02:09.621+0000] {subprocess.py:93} INFO - 	at org.apache.iceberg.BaseMetastoreCatalog.loadTable(BaseMetastoreCatalog.java:47)
[2025-07-19T18:02:09.621+0000] {subprocess.py:93} INFO - 	at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2406)
[2025-07-19T18:02:09.621+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ConcurrentHashMap.compute(Unknown Source)
[2025-07-19T18:02:09.621+0000] {subprocess.py:93} INFO - 	at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2404)
[2025-07-19T18:02:09.621+0000] {subprocess.py:93} INFO - 	at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2387)
[2025-07-19T18:02:09.621+0000] {subprocess.py:93} INFO - 	at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
[2025-07-19T18:02:09.621+0000] {subprocess.py:93} INFO - 	at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
[2025-07-19T18:02:09.621+0000] {subprocess.py:93} INFO - 	at org.apache.iceberg.CachingCatalog.loadTable(CachingCatalog.java:166)
[2025-07-19T18:02:09.621+0000] {subprocess.py:93} INFO - 	at org.apache.iceberg.spark.SparkCatalog.load(SparkCatalog.java:643)
[2025-07-19T18:02:09.621+0000] {subprocess.py:93} INFO - 	at org.apache.iceberg.spark.SparkCatalog.loadTable(SparkCatalog.java:159)
[2025-07-19T18:02:09.622+0000] {subprocess.py:93} INFO - 	at org.apache.iceberg.spark.source.IcebergSource.getTable(IcebergSource.java:107)
[2025-07-19T18:02:09.622+0000] {subprocess.py:93} INFO - 	at org.apache.iceberg.spark.source.IcebergSource.inferPartitioning(IcebergSource.java:90)
[2025-07-19T18:02:09.622+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Utils$.getTableFromProvider(DataSourceV2Utils.scala:82)
[2025-07-19T18:02:09.622+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.streaming.DataStreamWriter.startInternal(DataStreamWriter.scala:399)
[2025-07-19T18:02:09.622+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.streaming.DataStreamWriter.start(DataStreamWriter.scala:251)
[2025-07-19T18:02:09.622+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-07-19T18:02:09.622+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[2025-07-19T18:02:09.622+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[2025-07-19T18:02:09.622+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[2025-07-19T18:02:09.622+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-07-19T18:02:09.623+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-07-19T18:02:09.623+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-07-19T18:02:09.623+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-07-19T18:02:09.623+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-07-19T18:02:09.623+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-07-19T18:02:09.623+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-07-19T18:02:09.623+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Unknown Source)
[2025-07-19T18:02:09.658+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-19T18:02:09.658+0000] {subprocess.py:93} INFO -   File "/home/iceberg/spark/stream_to_bronze.py", line 93, in <module>
[2025-07-19T18:02:09.658+0000] {subprocess.py:93} INFO -     read_kafka(
[2025-07-19T18:02:09.658+0000] {subprocess.py:93} INFO -   File "/home/iceberg/spark/stream_to_bronze.py", line 89, in read_kafka
[2025-07-19T18:02:09.659+0000] {subprocess.py:93} INFO -     .start()
[2025-07-19T18:02:09.659+0000] {subprocess.py:93} INFO -      ^^^^^^^
[2025-07-19T18:02:09.659+0000] {subprocess.py:93} INFO -   File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/sql/streaming/readwriter.py", line 1527, in start
[2025-07-19T18:02:09.659+0000] {subprocess.py:93} INFO -   File "/opt/bitnami/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-07-19T18:02:09.659+0000] {subprocess.py:93} INFO -   File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
[2025-07-19T18:02:09.660+0000] {subprocess.py:93} INFO -   File "/opt/bitnami/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2025-07-19T18:02:09.660+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o67.start.
[2025-07-19T18:02:09.660+0000] {subprocess.py:93} INFO - : org.apache.iceberg.exceptions.RuntimeIOException: Failed to refresh the table
[2025-07-19T18:02:09.660+0000] {subprocess.py:93} INFO - 	at org.apache.iceberg.hadoop.HadoopTableOperations.refresh(HadoopTableOperations.java:126)
[2025-07-19T18:02:09.660+0000] {subprocess.py:93} INFO - 	at org.apache.iceberg.hadoop.HadoopTableOperations.current(HadoopTableOperations.java:84)
[2025-07-19T18:02:09.660+0000] {subprocess.py:93} INFO - 	at org.apache.iceberg.BaseMetastoreCatalog.loadTable(BaseMetastoreCatalog.java:47)
[2025-07-19T18:02:09.660+0000] {subprocess.py:93} INFO - 	at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2406)
[2025-07-19T18:02:09.661+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ConcurrentHashMap.compute(Unknown Source)
[2025-07-19T18:02:09.661+0000] {subprocess.py:93} INFO - 	at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2404)
[2025-07-19T18:02:09.661+0000] {subprocess.py:93} INFO - 	at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2387)
[2025-07-19T18:02:09.661+0000] {subprocess.py:93} INFO - 	at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
[2025-07-19T18:02:09.661+0000] {subprocess.py:93} INFO - 	at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
[2025-07-19T18:02:09.661+0000] {subprocess.py:93} INFO - 	at org.apache.iceberg.CachingCatalog.loadTable(CachingCatalog.java:166)
[2025-07-19T18:02:09.661+0000] {subprocess.py:93} INFO - 	at org.apache.iceberg.spark.SparkCatalog.load(SparkCatalog.java:643)
[2025-07-19T18:02:09.661+0000] {subprocess.py:93} INFO - 	at org.apache.iceberg.spark.SparkCatalog.loadTable(SparkCatalog.java:159)
[2025-07-19T18:02:09.661+0000] {subprocess.py:93} INFO - 	at org.apache.iceberg.spark.source.IcebergSource.getTable(IcebergSource.java:107)
[2025-07-19T18:02:09.661+0000] {subprocess.py:93} INFO - 	at org.apache.iceberg.spark.source.IcebergSource.inferPartitioning(IcebergSource.java:90)
[2025-07-19T18:02:09.661+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Utils$.getTableFromProvider(DataSourceV2Utils.scala:82)
[2025-07-19T18:02:09.661+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.streaming.DataStreamWriter.startInternal(DataStreamWriter.scala:399)
[2025-07-19T18:02:09.662+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.streaming.DataStreamWriter.start(DataStreamWriter.scala:251)
[2025-07-19T18:02:09.662+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-07-19T18:02:09.662+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[2025-07-19T18:02:09.662+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[2025-07-19T18:02:09.662+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[2025-07-19T18:02:09.662+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-07-19T18:02:09.662+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-07-19T18:02:09.662+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-07-19T18:02:09.662+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-07-19T18:02:09.662+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-07-19T18:02:09.662+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-07-19T18:02:09.662+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-07-19T18:02:09.663+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Unknown Source)
[2025-07-19T18:02:09.663+0000] {subprocess.py:93} INFO - Caused by: org.apache.hadoop.fs.s3a.UnknownStoreException: `s3a://warehouse/bronze/Reservations_raw/metadata/v0.metadata.json': getFileStatus on s3a://warehouse/bronze/Reservations_raw/metadata/v0.metadata.json: com.amazonaws.services.s3.model.AmazonS3Exception: The specified bucket does not exist (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: 1853B9094FDF1DDF; S3 Extended Request ID: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8; Proxy: null), S3 Extended Request ID: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8:NoSuchBucket: The specified bucket does not exist (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: 1853B9094FDF1DDF; S3 Extended Request ID: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8; Proxy: null)
[2025-07-19T18:02:09.663+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AUtils.translateException(S3AUtils.java:263)
[2025-07-19T18:02:09.663+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AUtils.translateException(S3AUtils.java:175)
[2025-07-19T18:02:09.663+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.s3GetFileStatus(S3AFileSystem.java:3858)
[2025-07-19T18:02:09.663+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.innerGetFileStatus(S3AFileSystem.java:3688)
[2025-07-19T18:02:09.663+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.lambda$exists$34(S3AFileSystem.java:4703)
[2025-07-19T18:02:09.663+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.statistics.impl.IOStatisticsBinding.lambda$trackDurationOfOperation$5(IOStatisticsBinding.java:499)
[2025-07-19T18:02:09.663+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.statistics.impl.IOStatisticsBinding.trackDuration(IOStatisticsBinding.java:444)
[2025-07-19T18:02:09.663+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.trackDurationAndSpan(S3AFileSystem.java:2337)
[2025-07-19T18:02:09.663+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.trackDurationAndSpan(S3AFileSystem.java:2356)
[2025-07-19T18:02:09.663+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.exists(S3AFileSystem.java:4701)
[2025-07-19T18:02:09.663+0000] {subprocess.py:93} INFO - 	at org.apache.iceberg.hadoop.HadoopTableOperations.getMetadataFile(HadoopTableOperations.java:241)
[2025-07-19T18:02:09.664+0000] {subprocess.py:93} INFO - 	at org.apache.iceberg.hadoop.HadoopTableOperations.refresh(HadoopTableOperations.java:106)
[2025-07-19T18:02:09.664+0000] {subprocess.py:93} INFO - 	... 28 more
[2025-07-19T18:02:09.664+0000] {subprocess.py:93} INFO - Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: The specified bucket does not exist (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: 1853B9094FDF1DDF; S3 Extended Request ID: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8; Proxy: null), S3 Extended Request ID: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8
[2025-07-19T18:02:09.664+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1879)
[2025-07-19T18:02:09.664+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1418)
[2025-07-19T18:02:09.664+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1387)
[2025-07-19T18:02:09.664+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
[2025-07-19T18:02:09.664+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814)
[2025-07-19T18:02:09.664+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
[2025-07-19T18:02:09.664+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
[2025-07-19T18:02:09.664+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
[2025-07-19T18:02:09.664+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
[2025-07-19T18:02:09.664+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
[2025-07-19T18:02:09.664+0000] {subprocess.py:93} INFO - 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
[2025-07-19T18:02:09.665+0000] {subprocess.py:93} INFO - 	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5456)
[2025-07-19T18:02:09.665+0000] {subprocess.py:93} INFO - 	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5403)
[2025-07-19T18:02:09.665+0000] {subprocess.py:93} INFO - 	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5397)
[2025-07-19T18:02:09.665+0000] {subprocess.py:93} INFO - 	at com.amazonaws.services.s3.AmazonS3Client.listObjectsV2(AmazonS3Client.java:971)
[2025-07-19T18:02:09.665+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.lambda$listObjects$11(S3AFileSystem.java:2595)
[2025-07-19T18:02:09.665+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.statistics.impl.IOStatisticsBinding.lambda$trackDurationOfOperation$5(IOStatisticsBinding.java:499)
[2025-07-19T18:02:09.665+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.Invoker.retryUntranslated(Invoker.java:414)
[2025-07-19T18:02:09.665+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.Invoker.retryUntranslated(Invoker.java:377)
[2025-07-19T18:02:09.665+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.listObjects(S3AFileSystem.java:2586)
[2025-07-19T18:02:09.665+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.s3GetFileStatus(S3AFileSystem.java:3832)
[2025-07-19T18:02:09.665+0000] {subprocess.py:93} INFO - 	... 37 more
[2025-07-19T18:02:09.665+0000] {subprocess.py:93} INFO - 
[2025-07-19T18:02:09.684+0000] {subprocess.py:93} INFO - 25/07/19 18:02:09 INFO SparkContext: Invoking stop() from shutdown hook
[2025-07-19T18:02:09.684+0000] {subprocess.py:93} INFO - 25/07/19 18:02:09 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-07-19T18:02:09.690+0000] {subprocess.py:93} INFO - 25/07/19 18:02:09 INFO SparkUI: Stopped Spark web UI at http://8b44f3d35cfa:4040
[2025-07-19T18:02:09.695+0000] {subprocess.py:93} INFO - 25/07/19 18:02:09 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-07-19T18:02:09.702+0000] {subprocess.py:93} INFO - 25/07/19 18:02:09 INFO MemoryStore: MemoryStore cleared
[2025-07-19T18:02:09.702+0000] {subprocess.py:93} INFO - 25/07/19 18:02:09 INFO BlockManager: BlockManager stopped
[2025-07-19T18:02:09.709+0000] {subprocess.py:93} INFO - 25/07/19 18:02:09 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-07-19T18:02:09.710+0000] {subprocess.py:93} INFO - 25/07/19 18:02:09 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-07-19T18:02:09.713+0000] {subprocess.py:93} INFO - 25/07/19 18:02:09 INFO SparkContext: Successfully stopped SparkContext
[2025-07-19T18:02:09.713+0000] {subprocess.py:93} INFO - 25/07/19 18:02:09 INFO ShutdownHookManager: Shutdown hook called
[2025-07-19T18:02:09.713+0000] {subprocess.py:93} INFO - 25/07/19 18:02:09 INFO ShutdownHookManager: Deleting directory /tmp/spark-c6c319e4-cb98-4012-a3a2-1cc239994a45
[2025-07-19T18:02:09.714+0000] {subprocess.py:93} INFO - 25/07/19 18:02:09 INFO ShutdownHookManager: Deleting directory /tmp/spark-c6c319e4-cb98-4012-a3a2-1cc239994a45/pyspark-b3ab11a3-c16b-4623-b1fb-5153434f51a7
[2025-07-19T18:02:09.715+0000] {subprocess.py:93} INFO - 25/07/19 18:02:09 INFO ShutdownHookManager: Deleting directory /tmp/spark-c6c42dc1-efff-4249-bba7-1f5a9b978795
[2025-07-19T18:02:09.718+0000] {subprocess.py:93} INFO - 25/07/19 18:02:09 INFO MetricsSystemImpl: Stopping s3a-file-system metrics system...
[2025-07-19T18:02:09.718+0000] {subprocess.py:93} INFO - 25/07/19 18:02:09 INFO MetricsSystemImpl: s3a-file-system metrics system stopped.
[2025-07-19T18:02:09.718+0000] {subprocess.py:93} INFO - 25/07/19 18:02:09 INFO MetricsSystemImpl: s3a-file-system metrics system shutdown complete.
[2025-07-19T18:02:09.750+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-19T18:02:09.756+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-19T18:02:09.757+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=restaurant_pipeline, task_id=stream_to_bronze, execution_date=20250719T180000, start_date=20250719T180205, end_date=20250719T180209
[2025-07-19T18:02:09.769+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2025-07-19T18:02:09.769+0000] {configuration.py:1050} WARNING - section/key [smtp/smtp_user] not found in config
[2025-07-19T18:02:09.769+0000] {email.py:270} INFO - Email alerting: attempt 1
[2025-07-19T18:02:09.772+0000] {configuration.py:1050} WARNING - section/key [smtp/smtp_user] not found in config
[2025-07-19T18:02:09.773+0000] {email.py:270} INFO - Email alerting: attempt 1
[2025-07-19T18:02:09.773+0000] {taskinstance.py:2007} ERROR - Failed to send email to: ['your@email.com']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1681, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1744, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2420, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2005, in handle_failure
    self.email_alert(error, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2422, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2025-07-19T18:02:09.779+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 918 for task stream_to_bronze (Bash command failed. The command returned a non-zero exit code 1.; 223)
[2025-07-19T18:02:09.823+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-07-19T18:02:09.848+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
